# Generated by Django 5.0.6 on 2024-07-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisement',
        ),
    ]
